### ISSUE TITLE
[特性讨论] - 多用户系统 （Multi-User Support）

### ISSUE THREAD

**Issue by imiskolee** [flike/kingshard#184]
### 特性讨论
------

#### 背景描述

为了实现多租户系统，并且为了在Mysql的物理连接中进行资源区分，现在我正在实现多用户特性。

#### 配置文件参考

```yaml
addr : 0.0.0.0:9696
users:
- 
 user: root
 password: root

-
 user: user_1
 password: pass_1

-
 user: user_2
 password: pass_2

-
 user: user_3
 password: pass_3

-
 user: user_4
 password: pass_4

log_level : debug
#log_sql: off
proxy_charset: utf8

nodes :
-
    name : node1
    max_conns_limit : 32
    users:
    -
      user: root
      password: root
    master : 10.211.55.3:3306

schema :
    db : 
    nodes: [node1]
    default: node1
    shard:
    -

```

##### 实现方案

```go
//新增一个UserPool来包裹backend.DB来实现用户级连接池
type UserPool struct {
	sync.RWMutex
	pools map[string]*DB
}

```

ps1： 以上方案已经初步实现。

ps2: 现在向大家征集需求，以及更好的实现方案。
