### ISSUE TITLE
[Bug] 当连接kingshard的时候，不指定数据库将有几率出错。

### ISSUE THREAD

**Issue by imiskolee** [flike/kingshard#185]
Bug重现办法

```yaml

addr : 0.0.0.0:9696

user :  root
password : root

log_sql: on

nodes :
-
    name : node1
    max_conns_limit : 5
    user :  root
    password : root
    master : 127.0.0.1:3306
    down_after_noalive : 32

schema :
    db :
    nodes: [node1]
    default: node1
    shard:
    -
```

1. 使用mysql cli 连接 mysql -h127.0.0.1 -P9696 -uroot -proot
2. 进入到mysql cli之后，进行use动作。
3. 退出mysql cli
4. 不断尝试命令1，将有几率产生`ERROR 1046 (3D000): No database selected` 错误，几率与max_conns_limit有直接关系

===========

猜测原因为：连接复用的时候该对种场景支持有问题导致的
