### ISSUE TITLE
读写分离问题

### ISSUE THREAD

**Issue by colben** [flike/kingshard#531]
# 环境
- CentOS7.4
- Kingshard Git commit:19a9415
- MySQL 5.7.27 一主一从

# 配置文件
```yml
addr: 0.0.0.0:3306
prometheus_addr: 127.0.0.1:9898
user_list:
- user: kingshard
  password: kingshard
web_addr: 0.0.0.0:9797
web_user: admin
web_password: admin
#log_path: /var/log/kingshard/
log_level: debug
log_sql: on
#slow_log_time: 100
#blacklist_sql_file: /var/lib/kingshard/blacklist
allow_ips: 127.0.0.1,192.168.0.0/24
proxy_charset: utf8mb4

nodes:
- name: node0
  max_conns_limit: 256
  user: ks
  password: ks_P@sswo2d
  master: 192.168.1.100:3306
  slave: 192.168.1.101:3306
  down_after_noalive: 32

schema_list:
- user: kingshard
  nodes:
  - node0
  default: node0
  shard:
  -
```

# 问题
- 目前，连接 kingshard 执行 selelct 语句时，每次都是在从库(192.168.1.101)上执行，怎么实现 select 语句随机上主库和从库上执行？
- 怎么禁用 prometheus 监控，我这里没有部署 prometheus，不想浪费资源去监听端口
