### ISSUE TITLE
Always show error "parepre error connection was bad"

### ISSUE THREAD

**Issue by fuxiaohei** [flike/kingshard#63]
I write simple test golang code with [xorm](https://github.com/go-xorm/xorm) to connect kingshard, and run inserts and selects in range.

the ks yaml:
```yaml
# server listen addr
addr : 0.0.0.0:9696

# server user and password
user :  kingshard
password : kingshard

#if set log_path, the sql log will write into log_path/sql.log,the system log
#will write into log_path/sys.log
log_path : ./

# log level[debug|info|warn|error],default error
log_level : debug
#if set log_sql(on|off) off,the sql log will not output
#log_sql: off 
#only log the query that take more than slow_log_time ms
#slow_log_time : 100
# only allow this ip list ip to connect kingshard
#allow_ips: 127.0.0.1

# node is an agenda for real remote mysql server.
nodes :
- 
    name : node1 

    # default max conns for mysql server
    max_conns_limit : 100

    # all mysql in a node must have the same user and password
    user :  root
    password : fuxiaohei

    # master represents a real mysql master server 
    master : 127.0.0.1:3306

    # slave represents a real mysql salve server,and the number after '@' is 
    # read load weight of this slave.
    slave : 127.0.0.1:3307@1
    down_after_noalive : 32

# schema defines which db can be used by client and this db's sql will be executed in which nodes
schema :
    db : kingshard_test1
    nodes: [node1]
    default: node1      
    shard:
    -   
        table: locus
        key: baby_id
        nodes: [node1]
        type: hash
        locations: [4]
```

the db table:

```sql
CREATE TABLE `locus` (
	`li_id` INT(11) NOT NULL AUTO_INCREMENT,
	`baby_id` INT(11) NULL DEFAULT NULL,
	`li_coordinates` VARCHAR(100) NOT NULL,
	`li_bdmcoords` VARCHAR(100) NOT NULL,
	`li_title` VARCHAR(50) NOT NULL,
	`li_addtime` INT(11) NOT NULL,
	`li_battery` INT(11) NOT NULL,
	`li_start` INT(11) NOT NULL DEFAULT '0',
	`li_end` INT(11) NOT NULL DEFAULT '0',
	`li_type` TINYINT(4) NOT NULL,
	`li_accuracy` SMALLINT(6) NOT NULL DEFAULT '50',
	`li_dev_uuid` INT(11) NOT NULL DEFAULT '0',
	`li_steps` INT(11) NOT NULL DEFAULT '0',
	`li_runs` INT(11) NOT NULL DEFAULT '0',
	`li_calory` INT(11) NOT NULL DEFAULT '0',
	PRIMARY KEY (`li_id`)
)
```

the simple golang code:
```go
package main

import (
	"fmt"

	"math/rand"

	_ "github.com/go-sql-driver/mysql"
	"github.com/go-xorm/xorm"
)

func main() {
	engine, err := xorm.NewEngine("mysql", "kingshard:kingshard@tcp(127.0.0.1:9696)/kingshard_test1")
	fmt.Println(engine, err)
	fmt.Println(engine.Ping())

	sql := "INSERT INTO `locus` (`baby_id`, `li_coordinates`, `li_bdmcoords`, `li_title`, `li_addtime`, `li_battery`, `li_start`, `li_end`, `li_type`, `li_accuracy`, `li_dev_uuid`, `li_steps`, `li_runs`, `li_calory`) VALUES (%d, '24.4884,118.1823', '', '思明区望海路', 1447916575, 100, 1447916565, 1447916938, 5, 55, 25121, 0, 0, 0);"

	mm := []int{}
	func() {
		for i := 0; i < 100; i++ {
			m := rand.Intn(9999) + 1
			_, err = engine.Exec(fmt.Sprintf(sql, m))
			fmt.Println("insert", i, err)
			mm = append(mm, m)
		}
	}()  // maybe xorm close connection session with defer statement, so use function block, but seem useless.

	sql = "SELECT li_id FROM locus WHERE baby_id = ? LIMIT 1"
	func() {
		for i, m := range mm {
			_, err := engine.Query(sql, m)
			fmt.Println("select", i, err)
		}
	}()
}
```

Then, start kingshard and run go code:

```
insert 70 <nil>
insert 71 <nil>
insert 72 <nil>
insert 73 <nil>
insert 74 <nil>
insert 75 <nil>
insert 76 <nil>
insert 77 <nil>
insert 78 Error 1105: parepre error 3 connection was bad
insert 79 Error 1105: parepre error 3 connection was bad
insert 80 <nil>
insert 81 <nil>
insert 82 <nil>
insert 83 Error 1105: parepre error 3 connection was bad
insert 84 Error 1105: parepre error 3 connection was bad
insert 85 <nil>
insert 86 <nil>
insert 87 <nil>
insert 88 <nil>
insert 89 Error 1105: parepre error 3 connection was bad
insert 90 <nil>
insert 91 <nil>
insert 92 <nil>
insert 93 <nil>
insert 94 Error 1105: parepre error 3 connection was bad
insert 95 Error 1105: parepre error 3 connection was bad
insert 96 <nil>
insert 97 <nil>
insert 98 <nil>
insert 99 Error 1105: parepre error 3 connection was bad
select 0 Error 1105: parepre error 3 connection was bad
select 1 <nil>
select 2 <nil>
select 3 <nil>
select 4 <nil>
select 5 <nil>
select 6 <nil>
select 7 <nil>
select 8 <nil>
select 9 <nil>
select 10 <nil>
select 11 <nil>
select 12 <nil>
select 13 <nil>
select 14 <nil>
select 15 <nil>
select 16 <nil>
select 17 <nil>
select 18 <nil>
select 19 <nil>
select 20 <nil>
select 21 <nil>
select 22 <nil>
select 23 <nil>
select 24 <nil>
select 25 <nil>
select 26 <nil>
select 27 <nil>
select 28 Error 1105: parepre error 3 connection was bad
select 29 Error 1105: parepre error 3 connection was bad
select 30 Error 1105: parepre error 3 connection was bad
select 31 Error 1105: parepre error 3 connection was bad
select 32 Error 1105: parepre error 3 connection was bad
select 33 Error 1105: parepre error 3 connection was bad 
```

it blocks when `select 33`.
